version: "3.8"

services:
  app:
    image: cdciudad-server
    environment:
      - MONGODB_URL="mongodb://db:27017/cdciudad"
    depends_on:
      - db
    ports:
      - "8000:80"


  db:
    image: mongo
    volumes: 
      - ./mongo/data:/data/db
    ports:
      - "27017:27017"